### ISSUE TITLE
usage in wildfly-maven-plugin

### ISSUE THREAD

**Issue by t1** [wildfly-extras/wildfly-graphql-feature-pack#100]
I've tried to use the wildfly-maven-plugin to build a Docker image ([see blog](https://www.wildfly.org//news/2022/08/04/wildfly-maven-docker/)), but it doesn't copy the modules. If I'm doing it wrong, there should be some documentation ;-)

My `pom.xml` contains:

```xml
<plugin>
    <groupId>org.wildfly.plugins</groupId>
    <artifactId>wildfly-maven-plugin</artifactId>
    <version>4.0.0.Beta3</version>
    <configuration>
        <feature-packs>
            <feature-pack>
                <location>org.wildfly:wildfly-galleon-pack:26.1.1.Final</location>
            </feature-pack>
            <feature-pack>
                <location>org.wildfly.extras.graphql:wildfly-microprofile-graphql-feature-pack:1.7.0.Final</location>
            </feature-pack>
        </feature-packs>
        <layers>
            <layer>microprofile-platform</layer>
        </layers>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>package</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by jmartisk** [comment]
I've never done this, but shouldn't you add the  `microprofile-graphql` layer in the `<layers>` element?

**Comment by t1** [comment]
That worked, thanks! Actually, I still got a data fetching exception without any logs, so I also added `core-server`, but then it works like a charm.

Note to myself: the layers are documented [here](https://docs.wildfly.org/26.1/Bootable_Guide.html#wildfly_layers)
