### ISSUE TITLE
Redeployment of the same artifact causes java.lang.IllegalArgumentException in graphql response

### ISSUE THREAD

**Issue by mircea-cm** [wildfly-extras/wildfly-graphql-feature-pack#11]
Subsequent redeployments of the same artifact cause java.lang.IllegalArgumentException in graphql response

Reproduce steps:

- clone the repo
- go to quickstart directory
- **galleon.sh provision ./provision.xml --dir=wildfly**
- start the server with **./wildfly/bin/standalone.sh**
- open another terminal in quickstart directory and run **mvn package wildfly:deploy**
- open [graphql-ui](http://localhost:8080/quickstart/graphql-ui) and add the following:
```
query allFilms {
  allFilms {
		title
  }
}
```
- first time works
- while server is running deploy the war again with **mvn package wildfly:deploy**
- running the same query in  [graphql-ui](http://localhost:8080/quickstart/graphql-ui) outputs:
```
{
  "errors": [
    {
      "message": "Server Error",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "allFilms",
        0,
        "title"
      ],
      "extensions": {
        "exception": "java.lang.IllegalArgumentException",
        "classification": "DataFetchingException",
        "code": "illegal-argument"
      }
    },
... same error 2 more times
  ],
  "data": {
    "allFilms": [
      {
        "title": null
      },
      {
        "title": null
      },
      {
        "title": null
      }
    ]
  }
}
```

Also can be reproduced with a filesystem deployment:
- manual copy quickstart.war in **./wildfly/standalone/deployments**
- after it starts and a query is made, trigger a redeploy with  **mv wildfly/standalone/deployments/quickstart.war.deployed wildfly/standalone/deployments/quickstart.war.dodeploy**
- running the same query causes an error.

**Comment by jmartisk** [comment]
Hi @mircea-cm ! This is a known issue, I track it as part of https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/6
It's a problem in one underlying library, graphql-java, and it has been fixed in that library, we will need to wait until they release a new version and until SmallRye GraphQL migrates to that version.
Let me close this issue as a duplicate then. If you have more concerns, feel free to comment on #6. Thanks!
