### ISSUE TITLE
After upgrading to SRGQL 1.0.12, move to using the smallrye-graphql-client-all dependency

### ISSUE THREAD

**Issue by jmartisk** [wildfly-extras/wildfly-graphql-feature-pack#13]
.. and clean up the dependencies in `quickstart/pom.xml`

**Comment by t1** [comment]
... but WildFly already contains implementations for JAX-RS, etc.?!?

**Comment by jmartisk** [comment]
WildFly does, but the quickstart uses the client libraries as a **standalone** application outside WildFly (and only for testing right now).

Running the client INSIDE the container is not fully supported yet - that is planned through https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/3 and will require including the client jars as static modules for WildFly. Of course you can run the client inside WildFly now already, but it requires you to include the JARs in the deployment (and manage them yourself manually), which is not ideal.

**Comment by jmartisk** [comment]
I'm closing this because we've already moved to 1.0.12 and the quickstart now uses `smallrye-graphql-client-all` for its testing dependencies.
#3 is the task to fully support running the client in-container without managing the deps manually.
