### ISSUE TITLE
The URL of the 2.1.0 overlay.zip contains `SNAPSHOT`

### ISSUE THREAD

**Issue by t1** [wildfly-extras/wildfly-graphql-feature-pack#147]
The URL to download the `overlay.zip` is

`https://github.com/wildfly-extras/wildfly-graphql-feature-pack/releases/download/2.1.0.Final/wildfly-28.0.0.Final-mp-graphql-2.1.0.Final-SNAPSHOT-overlay.zip`

while it should be

`https://github.com/wildfly-extras/wildfly-graphql-feature-pack/releases/download/2.1.0.Final/wildfly-28.0.0.Final-mp-graphql-2.1.0.Final-overlay.zip`

**Comment by jmartisk** [comment]
Ah, that wasn't just the URL, I'd actually uploaded the build created before removing the `SNAPSHOT` word during the release process. Fixed now, thanks for pointing this out.
