### ISSUE TITLE
java.sql.Date NoClassDefFoundError

### ISSUE THREAD

**Issue by drohne1673** [wildfly-extras/wildfly-graphql-feature-pack#177]
WF30 with smallrye featurepack 2.2.0.Final this includes SmallRye GraphQL 2.5.0. This works fine.

After upgrading to the latest Version WF32 with smallrye featurepack 2.4.0.Final this includes SmallRye GraphQL 2.9.1. the following problem occurs:

```
Caused by: java.lang.NoClassDefFoundError: java/sql/Date
2024-08-06T11:44:50.801279208Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.scalarValue(VertxTypesafeGraphQLClientProxy.java:347)
```
this line was added between 2.5.2 and 2.9*
```
        if (value instanceof java.sql.Date) {
            return Json.createValue(value.toString());
        }
```

we run openjdk-17-jre-headless on debian bookworm

**Comment by drohne1673** [comment]
sorry wrong project :)

**Comment by jmartisk** [comment]
actually yeah I think this will have to be fixed in the feature pack, so this was correct :) nevermind, let's continue in the smallrye-graphql repo

**Comment by drohne1673** [comment]
my idea to move it to the other project was because the dependency on the class is in graphql itself. cant say if there is another recommended way of installing it other than the feature pack :)
