### ISSUE TITLE
graphql.schema.validation.InvalidSchemaException: invalid schema not implementing interface

### ISSUE THREAD

**Issue by drohne1673** [wildfly-extras/wildfly-graphql-feature-pack#180]
I raised this question on graphql-java -> https://github.com/graphql-java/graphql-java/discussions/3701 but they recommended it here:

i was running WildFly 30 → Feature pack 2.2.0.Final →SmallRye GraphQL 2.5.0 included. -> graphql-java 20.2
i now upgraded to WildFly 33 →Feature pack 2.4.1.Final →SmallRye GraphQL 2.9.1 included -> graphql-java 22.1

now i get these errors when starting up:

> Caused by: graphql.schema.validation.InvalidSchemaException: invalid schema:
> object type 'BasicOrder' does not implement interface 'Order' because field 'orderId' is defined as 'String' type and not as 'String!' type
> object type 'BasicOrder' does not implement interface 'Order' because field 'orderState' is defined as 'OrderState' type and not as 'OrderState!' type"}}

the classes are quite simple:

```
public interface Order {
	default String getOrderType() {
		return getClass().getSimpleName();
	}

	@NonNull
	String getOrderId();

	@NonNull
	OrderState getOrderState();
}
```

and

```
@Description("A generic order for basic orderInformation to return to the client")
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
public class BasicOrder implements Order {

	@NonNull
	@Setter(NONE) // not in GraphQL Input
	private String orderId;

	@NonNull
	@Setter(NONE) // not in GraphQL Input
	private OrderState orderState;
}
```

has aynone an idea why this may cause graphql trouble ? thanks

**Comment by jmartisk** [comment]
Hi, we recently had a very similar report here: https://github.com/smallrye/smallrye-graphql/discussions/2171
It's related to the usage of Lombok, which we generally don't support. Please read this discussion, there's a proposed workaround. Let me know if it works for you.

**Comment by drohne1673** [comment]
thank you @jmartisk this fixed my issue
