### ISSUE TITLE
provision.xml link broken

### ISSUE THREAD

**Issue by mchoma** [wildfly-extras/wildfly-graphql-feature-pack#26]
Reading https://www.wildfly.org/news/2020/08/13/Introducing-the-WildFly-GraphQL-feature-pack/

I get 404 for https://www.wildfly.org/news/2020/08/13/Introducing-the-WildFly-GraphQL-feature-pack/%7Bprojectlink%7D/provision.xml

I assume correct is https://github.com/wildfly-extras/wildfly-graphql-feature-pack/blob/master/provision.xml ?

**Comment by jmartisk** [comment]
Thanks a lot @mchoma for noticing :) PR submitted to fix it
