### ISSUE TITLE
Fix problems when multiple GraphQL deployments exist in one WildFly instance, or when the same deployment is redeployed

### ISSUE THREAD

**Issue by jmartisk** [wildfly-extras/wildfly-graphql-feature-pack#6]
One known problem right now is https://github.com/graphql-java/graphql-java/issues/1983
There might be more

**Comment by jmartisk** [comment]
Test that verifies the caching problem was added through https://github.com/wildfly-extras/wildfly-graphql-feature-pack/commit/21393b9496fa51567037bd694c856196921725fd (test is ignored for now, because the solution is not in place yet)

**Comment by mircea-cm** [comment]
Hi @jmartisk, thanks for the response.

**Comment by jmartisk** [comment]
Fix is in graphql-java (https://github.com/graphql-java/graphql-java/pull/1984) but we will need a 16.0 release and upgrade to it in SmallRye GraphQL

**Comment by jmartisk** [comment]
Graphql-java 16.1 is in and I'm not aware of any issues with multiple deployments anymore, so this should work with current master, and with 1.0.0.Final which I'm about to release very soon.
