### ISSUE TITLE
Provide for 1.5.0

### ISSUE THREAD

**Issue by t1** [wildfly-extras/wildfly-graphql-feature-pack#96]
It would be nice to have the feature pack for SmallRye GraphQL 1.5.0, which was just released yesterday.

see https://github.com/smallrye/smallrye-graphql/releases/tag/1.5.0

**Comment by jmartisk** [comment]
Yes that will come as version 1.7, I'll aim to have a look next week, I'm just not sure it will be extra smooth - because SmallRye GraphQL 1.5.0 contains a few quite disruptive changes

**Comment by jmartisk** [comment]
1.7.0 released (might need a bit more time to appear in maven central)
